### ISSUE TITLE
Save and restore the model?

### ISSUE THREAD

**Issue by AndRossi** [nju-websoft/RSN#2]
Hello, as far as I can see there are no ways to save and restore a model when the training is over. It would be nice to have that feature :)

**Comment by guolingbing** [comment]
Hi, sorry for my late reply. I was quite busy preparing my English test last two months.

Thank you for your suggestion. As we can easily use [tf.train.Saver](https://www.tensorflow.org/api_docs/python/tf/train/Saver) to save or restore a model, we don't consider this as a necessary feature :)
