### ISSUE TITLE
Concerning the attribute files of the datasets

### ISSUE THREAD

**Issue by DexterZeng** [nju-websoft/RSN#3]
Hi, thank you for sharing the code. It has been really helpful! However, I cannot find the attribute files, which should be essential for implementing JAPE and GCN-Align. I wonder whether you can provide these files, or am I missing something?

Many thanks,
Weixin.

**Comment by guolingbing** [comment]
Hi, sorry for my late reply. I was busy preparing my English test  last two months.

I've updated a complete version of the EA datasets, named entity-alignment-full-data.7z. It includes not only the attribute files, but also the datsets with different proportions.

If you have any problems, please do not hesitate to contact me.

**Comment by DexterZeng** [comment]
Hi, thanks for your response!

Many thanks,
Weixin.

**Comment by DexterZeng** [comment]
Hi,

It seems that some files under fold xx/jape/ cannot be directly opened. For instance, under en_de_15k_V1/jape/, ent_attrs_2 can be opened, while ent_attrs_1 cannot be opened no matter using gedit, numpy or pickle.  Is there something I am misunderstanding?

Many thanks,
Weixin.
